- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site_main
  
  
  tasks: 
#    - name: "Criando um arquivo no servidor"
#      shell: "echo 'escrevendo algo no servidor' >> teste.txt"

    - name: "Executa o apt-get update"
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: "Instala pacotes"
      apt: 
        name: ['nginx', 'git']
        state: latest
      become: yes
    
    - name: "Adicionar a chave ssh do git"
      copy: >
        src=/home/ubuntu/daltro/ssh/id_rsa
        dest=/home/ubuntu/id_rsa
        owner=ubuntu
        group=ubuntu
        mode=0600
      
    - name: "Clonar o repositório do git"
      git: >
        repo=git@github.com:osanam-giordane/MobEAD.git
        key_file=/home/ubuntu/id_rsa
        dest=/home/ubuntu/daltro
        accept_hostkey=yes
        force=yes
        recursive=no
        
    - name: "Copiar os arquivos da aplicação para o nginx"
      copy: >
        src=/home/ubuntu/daltro/
        dest=/var/www/html
        owner=ubuntu
        group=ubuntu
        remote_src=true
        mode=0600    
 
        
   
